"""create_revenues_table

Revision ID: 04fae61fae6e
Revises: 838bb293986c
Create Date: 2025-02-26 12:10:20.528261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04fae61fae6e'
down_revision: Union[str, None] = '838bb293986c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenues',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('geo_code', sa.String(length=10), nullable=False),
        sa.Column('geo_type', sa.String(length=10), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('median_revenue', sa.Float(), nullable=True),
        sa.Column('poverty_rate', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenues_geo_code'), 'revenues', ['geo_code'], unique=False)
    op.create_index(op.f('ix_revenues_geo_type'), 'revenues', ['geo_type'], unique=False)
    op.create_index('ix_revenues_geo_type_geo_code_year', 'revenues', ['geo_type', 'geo_code', 'year'], unique=False)
    op.create_index(op.f('ix_revenues_year'), 'revenues', ['year'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revenues_year'), table_name='revenues')
    op.drop_index('ix_revenues_geo_type_geo_code_year', table_name='revenues')
    op.drop_index(op.f('ix_revenues_geo_type'), table_name='revenues')
    op.drop_index(op.f('ix_revenues_geo_code'), table_name='revenues')
    op.drop_table('revenues')
    # ### end Alembic commands ###
