"""Create births table

Revision ID: 4665133fb108
Revises: 
Create Date: 2025-02-14 10:05:21.839663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4665133fb108'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('births',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo', sa.String(), nullable=False),
    sa.Column('geo_object', sa.String(), nullable=False),
    sa.Column('time_period', sa.Integer(), nullable=False),
    sa.Column('obs_value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_births_id'), 'births', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_births_id'), table_name='births')
    op.drop_table('births')
    # ### end Alembic commands ###
