"""create_family_employment_table

Revision ID: bf30546ac142
Revises: ff9a1d5f46e4
Create Date: 2025-02-27 11:08:03.829015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf30546ac142'
down_revision: Union[str, None] = 'ff9a1d5f46e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('family_employment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('geo_code', sa.String(length=10), nullable=False),
        sa.Column('year', sa.Integer(), nullable=False),
        sa.Column('age_group', sa.String(5), nullable=False),
        sa.Column('tf12', sa.String(5), nullable=False),
        sa.Column('number', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_employment_age_group'), 'family_employment', ['age_group'], unique=False)
    op.create_index(op.f('ix_family_employment_geo_code'), 'family_employment', ['geo_code'], unique=False)
    op.create_index(op.f('ix_family_employment_tf12'), 'family_employment', ['tf12'], unique=False)
    op.create_index(op.f('ix_family_employment_year'), 'family_employment', ['year'], unique=False)
    op.create_index('ix_family_employment_geo_code_year_age_group_tf12', 'family_employment',
                    ['geo_code', 'year', 'age_group', 'tf12'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_family_employment_geo_code_year_age_group_tf12', table_name='family_employment')
    op.drop_index(op.f('ix_family_employment_year'), table_name='family_employment')
    op.drop_index(op.f('ix_family_employment_tf12'), table_name='family_employment')
    op.drop_index(op.f('ix_family_employment_geo_code'), table_name='family_employment')
    op.drop_index(op.f('ix_family_employment_age_group'), table_name='family_employment')
    op.drop_table('family_employment')
    # ### end Alembic commands ###
