"""create_populations_table

Revision ID: ff9a1d5f46e4
Revises: 04fae61fae6e
Create Date: 2025-02-26 12:34:45.049715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff9a1d5f46e4'
down_revision: Union[str, None] = '04fae61fae6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted! ###
    op.create_table('populations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('nivgeo', sa.String(length=10), nullable=False),
        sa.Column('codgeo', sa.String(length=10), nullable=False),
        sa.Column('libgeo', sa.String(), nullable=False),
        sa.Column('sexe', sa.String(length=1), nullable=False),
        sa.Column('aged100', sa.String(length=3), nullable=False),
        sa.Column('nb', sa.Float(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_populations_codgeo'), 'populations', ['codgeo'], unique=False)
    op.create_index('ix_populations_codgeo_sexe_aged100', 'populations', ['codgeo', 'sexe', 'aged100'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted! ###
    op.drop_index('ix_populations_codgeo_sexe_aged100', table_name='populations')
    op.drop_index(op.f('ix_populations_codgeo'), table_name='populations')
    op.drop_table('populations')
    # ### end Alembic commands ###
